config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/tv_shows', to: 'tv_shows#index'
  get '/welcome', to: 'tv_shows#welcome'
  root 'tv_shows#welcome'
  resources :tv_shows do
    resources :episodes
    get 'search', on: :collection
    resources :actors, only: [:new, :create]
    get 'about', on: :member
  end
end

app/models/actor.rb
class Actor < ApplicationRecord
  has_and_belongs_to_many :tv_shows
  has_one_attached :image
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/episode.rb
class Episode < ApplicationRecord
  belongs_to :tv_show
end

app/models/film_location.rb
class FilmLocation < ApplicationRecord
  belongs_to :tv_show
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/genre_tv_show.rb
class GenreTvShow < ApplicationRecord
  belongs_to :genre
  belongs_to :tv_show
end

app/models/nationality.rb
class Nationality < ApplicationRecord
    has_many :tv_shows
end

app/models/tv_show.rb
class TvShow < ApplicationRecord
    has_many :film_locations, inverse_of: :tv_show
    accepts_nested_attributes_for :film_locations
    has_many :episodes, dependent: :destroy
    validates :name, presence: true
    belongs_to :nationality
    belongs_to :user
    has_and_belongs_to_many :actors
    has_many :genre_tv_shows, dependent: :destroy
    has_many :genres, through: :genre_tv_shows
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tv_shows, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :image
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  def new
      @tv_show = TvShow.find(params[:tv_show_id])
      @actor = @tv_show.actors.build
  end

  def create
      @tv_show = TvShow.find(params[:tv_show_id])
      @actor = @tv_show.actors.create!(actor_params)
      redirect_to @tv_show
  end

  private

  def actor_params
    params.require(:actor).permit(:first_name, :last_name, :age, :image)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
  
      protected
  
      def configure_permitted_parameters
          devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name])
      end
  end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
    def create
        @tv_show = TvShow.find(params[:tv_show_id])
        @episode = @tv_show.episodes.create(episode_params)
        redirect_to tv_show_path(@tv_show)
    end

    private
    def episode_params
        params.require(:episode).permit(:episode_number, :title, :summary)
    end
end

app/controllers/tv_shows_controller.rb
class TvShowsController < ApplicationController
  before_action :set_tv_show, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[welcome]

  # GET /tv_shows or /tv_shows.json
  def index
    @tv_shows = TvShow.order(:name).page(params[:page]).per(15)
  end

  # GET /tv_shows/1 or /tv_shows/1.json
  def show
  end

  # GET /tv_shows/new
  def new
    @tv_show = TvShow.new
    2.times { @tv_show.film_locations.build }
  end

  # GET /tv_shows/1/edit
  def edit
  end

  # GET /tv_shows/1/about
  def about
    @about = "Copyright 2022"
    @tv_show = TvShow.find(params[:id])
  end

  # GET /tv_shows/search
  def search
    @search = TvShow.find_by("name LIKE ?", "%#{params[:query]}%")
  end

  # POST /tv_shows or /tv_shows.json
  def create
    @tv_show = current_user.tv_shows.build(tv_show_params)
    @tv_show.nationality = Nationality.find(params[:tv_show][:nationality_id]) || Nationality.last
    respond_to do |format|
      if @tv_show.save
        format.html { redirect_to tv_show_url(@tv_show), notice: "Creado Satisfactoriamente" }
        format.json { render :show, status: :created, location: @tv_show }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tv_show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tv_shows/1 or /tv_shows/1.json
  def update
    respond_to do |format|
      if @tv_show.update(tv_show_params)
        format.html { redirect_to tv_show_url(@tv_show), notice: "Tv show was successfully updated." }
        format.json { render :show, status: :ok, location: @tv_show }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tv_show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tv_shows/1 or /tv_shows/1.json
  def destroy
    @tv_show.destroy

    respond_to do |format|
      format.html { redirect_to tv_shows_url, notice: "Tv show was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tv_show
    @tv_show = TvShow.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def tv_show_params
    params.require(:tv_show).permit(
      :name,
      :summary,
      :release_date,
      :rating,
      :ruta_img,
      :nationality_id,
      film_locations_attributes: [:id, :name, :indoor],
      genre_ids: [],
    )
  end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/tv_shows_helper.rb
module TvShowsHelper
end

app/views/actors/create.html.erb
<h1>Actors#create</h1>
<p>Find me in app/views/actors/create.html.erb</p>

app/views/actors/new.html.erb
<h1>Add actors to tv_show</h1>

<%= form_with(model:[@tv_show, @actor]) do |form| %>
    <div class="field">
        <%= form.label :first_name %>
        <%= form.text_field :first_name %>
    </div>

    <div class="field">
        <%= form.label :last_name %>
        <%= form.text_field :last_name %>
    </div>

    <div class="field">
        <%= form.label :age %>
        <%= form.number_field :age %>
    </div>

    <div class="field">
        <%= form.label :image %>
        <%= form.file_field :image %>
    </div>
    <br>
    <div class="field">
        <%= form.submit %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyFavorite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<body>
  <% if user_signed_in? %>
      <div>
          <p>Bienvenido <%= current_user.email %>!!</p>
          <%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete %>
      </div>
  <% else %>
      <div style="text-align:right">
          <%= link_to 'Registro', new_user_registration_path %> |
          <%= link_to 'Ingresar', new_user_session_path %>
      </div>
  <% end %>
  <%= yield %>
</body>
</html>

app/views/tv_shows/_form.html.erb
<%= form_with(model: tv_show) do |form| %>
  <% if tv_show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tv_show.errors.count, "error") %> prohibited this tv_show from being saved:</h2>

      <ul>
        <% tv_show.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :'Nombre' %><br>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :'Ruta Imagen' %><br>
    <%= form.text_field :ruta_img %>
  </div>

  <div class="field">
    <%= form.label :'Sinopsis' %><br>
    <%= form.text_area :summary %>
  </div>

  <div class="field">
    <%= form.label :'Fecha de Estreno' %><br>
    <%= form.datetime_select :release_date %>
  </div>

  <div class="field">
    <%= form.label :'Rating' %><br>
    <%= form.text_field :rating %>
  </div>

  <div class="field">
    <%= form.label :'Nacionalidad' %><br>
    <%= collection_select(:tv_show, :nationality_id, Nationality.all, :id, :name, prompt: true) %>
  </div> <br>  

  <div class="field">
        <%= form.collection_select(:genre_ids, Genre.all, :id, :name, { prompt: true }, { multiple: true }) %>
  </div><br>

<%= form.collection_check_boxes :genre_ids, Genre.all, :id, :name %>

<fieldset style="width:270px">
<legend>Film locations</legend>

<ul class="field">
    <%= form.fields_for :film_locations do |film_locations_form| %>
    <li>
      <%= film_locations_form.label :name %>
      <%= film_locations_form.text_field :name %>

      <%= film_locations_form.label :indoor %>
      <%= film_locations_form.check_box :indoor %>
    </li>
    <% end %>
</ul>
</fieldset>
  <div class="actions"> <br> <br>
    <%= form.submit %>
  </div>
<% end %>

app/views/tv_shows/about.html.erb
<h3>Acerca de:</h3>
<p><%= @tv_show.name %></p>
<p><%= @about %></p>
<%= link_to "Back", tv_shows_path %>

app/views/tv_shows/edit.html.erb
<header  class="title d-flex justify-content-center">
<h1>Editing Tv Show</h1>
</header>
<nav class="title d-flex justify-content-center">

<%= render "form", tv_show: @tv_show %>
</nav>

<footer>
<%= link_to "Show", @tv_show %> |
<%= link_to "Back", tv_shows_path %>
</footer>

app/views/tv_shows/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
    <div class="title d-flex justify-content-center">
    <h1>Tv Shows</h1>
    </div>
<%= link_to "Welcome", root_path %>
<div class="row">
<div class="table-responsive">
<table class="table">
  <thead>
    <tr>
      <th>Imagen</th>
      <th>Nombre</th>
      <th>Sinopsis</th>
      <th>Fecha de lanzamiento</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tv_shows.each do |tv_show| %>
      <tr>
        <td><%= image_tag(tv_show.ruta_img, title: tv_show.name, width: "80px") %></td>
        <td><%= tv_show.name %></td>
        <td><%= tv_show.summary %></td>
        <td><%= tv_show.release_date %></td>
        <td><%= tv_show.rating %></td>
        <td><%= image_tag(url_for(tv_show.nationality.flag_img)) %></td>
        
        <% if user_signed_in? %>
          <td>
            <%= link_to (tv_show) do %>
              <i class="material-icons">search</i>
            <% end %></td>
        <% end %>
        <% if (user_signed_in? && (current_user == tv_show.user)) %>
          <td>
            <%= link_to about_tv_show_path(tv_show) do %>
              <i class="material-icons">info</i>
            <% end %>
          </td>
          <td>
            <%= link_to edit_tv_show_path(tv_show) do %>
              <i class="material-icons">edit_note</i>
            <% end %>
          </td>
        <% elsif user_signed_in? && current_user.admin? %>
          <td>
            <%= link_to tv_show, method: :delete, data: { confirm: "¿Estás seguro?" } do %>
              <i class="material-icons">delete</i>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>
<br>
<%= paginate @tv_shows %>
<br>
<%= link_to "Nueva Serie", new_tv_show_path %> |
<%= link_to "Buscar Serie", search_tv_shows_path %>

app/views/tv_shows/new.html.erb
<h1>New Tv Show</h1>

<%= render 'form', tv_show: @tv_show %>

<%= link_to 'Back', tv_shows_path %>

app/views/tv_shows/search.html.erb
<%= form_with url: "/tv_shows/search", method: :get do |form| %>
    <%= form.label :query, "Buscar película o serie:" %>
    <%= form.text_field :query %>
    <%= form.submit "Buscar" %>
<% end %>

<% if @search %>

<p>
    <strong>Name:</strong>
    <%= @search.name %>
</p>

<p>
    <strong>Summary:</strong>
    <%#= @search.summary %>
</p>

<p>
    <strong>Release date:</strong>
    <%= @search.release_date %>
</p>

<p>
    <strong>Rating:</strong>
    <%= @search.rating %>
</p>
<% else %>
  <%= "***Ningun dato encontrado***" %>
<% end %>

<%= link_to 'Back', tv_shows_path %>

app/views/tv_shows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tv_show.name %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @tv_show.summary %>
</p>

<p>
  <strong>Release date:</strong>
  <%= @tv_show.release_date %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @tv_show.rating %>
</p>

<p>
  <strong>Nationality:</strong>
  <%= image_tag(url_for(@tv_show.nationality.flag_img)) %>
</p>

<p><strong>Film locations:</strong></p>
<ul>
    <% if @tv_show.film_locations %>
        <% @tv_show.film_locations.each do |film_location| %>
            <li><strong><%= film_location.name %>: </strong>
            <%= film_location.indoor ? "Indoor" : "Outdoor" %></li>
        <% end %>
    <% else %>
        <% "No Film Locations Added!!!" %>
    <% end %>
</ul>

<p><strong>Actors:</strong></p>
<ul>
    <% if @tv_show.actors %>
        <% @tv_show.actors.each do |actor| %>
            <li>
            <strong><%= actor.id %>: </strong><%= "#{actor.first_name} #{actor.last_name}" %>
            </li>
            <% if actor.image.attached? %>
                <li>
                    <%= cl_image_tag(actor.image.key, width: 120, height: 80) %>
                </li>
            <% end %>
        <% end %>
    <% else %>
        <% "No Actors Added!!!" %>
    <% end %>
</ul>

<h2>Listado de episodios</h2>
<% @tv_show.episodes.each do |episode| %>
    <p>
        <strong>Episode number:</strong>
        <%= episode.episode_number %>
    </p>

    <p>
        <strong>Title:</strong>
        <%= episode.title %>
    </p>

    <p>
        <strong>Summary:</strong>
        <%= episode.summary %>
    </p>
<% end %>

<h2>Agregue un episodio:</h2>
<%= form_with model: [@tv_show, @tv_show.episodes.build] do |form| %>
    <p>
        <%= form.label :episode_number %><br>
        <%= form.number_field :episode_number %>
    </p>
    <p>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
    </p>
    <p>
        <%= form.label :summary %><br>
        <%= form.text_area :summary %>
    </p>
    <p>
        <%= form.submit "Crear episodio" %>
    </p>
<% end %>

<p><strong>Genres:</strong></p>
<ul>
    <% if @tv_show.genres %>
        <% @tv_show.genres.each do |genre| %>
            <li><strong><%= "#{genre.id}" %>: </strong><%= genre.name %></li>
        <% end %>
    <% else %>
        <% "No Genres Added!!!" %>
    <% end %>
</ul>

<%= link_to "Edit", edit_tv_show_path(@tv_show) %> |
<%= link_to "Add actors", new_tv_show_actor_path(@tv_show) %> |
<%= link_to "Back", tv_shows_path %>

app/views/tv_shows/welcome.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS 
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">-->
    <h1 class="title d-flex justify-content-center">My Tv Series</h1>
  </head>
  <body>
  <%= link_to "Administración", tv_shows_path %>
    <section id="galeria" class="container">
        <div class="tex-center pt-5" >
        </div>
        <div class=row>
            <div class="col-lg-4">
            <%= image_tag("agatha.jpg", alt: "Iron Man") %>
            </div>
            <div class="col-lg-4">
            <%= image_tag("angry.jpg", alt: "Iron Man") %>
            </div>
            <div class="col-lg-4">
            <%= image_tag("blande.jpg", alt: "Iron Man") %>
            </div>
            <div class="col-lg-4">
            <%= image_tag("gameofthrones.jpg", alt: "Iron Man") %>
            </div>
            <div class="col-lg-4">
            <%= image_tag("jaws.jpg", alt: "Iron Man") %>
            </div>
            <div class="col-lg-4">
            <%= image_tag("Squid-Game.jpg", alt: "Iron Man") %>
            </div>
        </div>
    </section>
  </body>
</html>